# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_task_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='shared',
        ),
        migrations.AddField(
            model_name='task',
            name='shared',
            field=models.CharField(default=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
